# **Center Back Position**

## **Load CB Data**

In [1]:
import pandas as pd

cb_df = pd.read_csv('CB.csv', delimiter=';')
cb_df

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC,GOAL
0,0,0.0,3,1.00,9,0.33,0,0.0,0,0.0,0,0.0,6
1,0,0.0,4,0.75,0,0.00,0,0.0,1,1.0,0,0.0,4
2,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0,1
3,0,0.0,0,0.00,2,0.50,0,0.0,0,0.0,0,0.0,1
4,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,0,0.0,3,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0
1284,0,0.0,2,1.00,0,0.00,0,0.0,0,0.0,1,1.0,3
1285,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0,1
1286,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0
1287,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0

## **Prepare X and y**

In [2]:
X = cb_df.drop('GOAL', axis=1)
y = cb_df['GOAL']

In [3]:
X

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC
0,0,0.0,3,1.00,9,0.33,0,0.0,0,0.0,0,0.0
1,0,0.0,4,0.75,0,0.00,0,0.0,1,1.0,0,0.0
2,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0
3,0,0.0,0,0.00,2,0.50,0,0.0,0,0.0,0,0.0
4,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1283,0,0.0,3,0.00,0,0.00,0,0.0,0,0.0,0,0.0
1284,0,0.0,2,1.00,0,0.00,0,0.0,0,0.0,1,1.0
1285,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0
1286,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
1287,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0

In [4]:
y

0       6
1       4
2       1
3       1
4       0
       ..
1283    0
1284    3
1285    1
1286    0
1287    0
Name: GOAL, Length: 1288, dtype: int64

## **Training set and Testing set**

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.gaussian_process.kernels import RBF

length_scale = 1.0
rbf_kernel = RBF(length_scale=length_scale)
X_rbf = rbf_kernel(X)

X_train, X_test, y_train, y_test = train_test_split(X_rbf, y, train_size=.8, random_state=42)

In [6]:
X_train

array([[3.30245710e-19, 3.96103470e-03, 6.06530660e-01, ...,
        6.06530660e-01, 3.67879441e-01, 3.67879441e-01],
       [6.81752553e-17, 3.42696649e-05, 2.23130160e-01, ...,
        2.23130160e-01, 3.67879441e-01, 3.67879441e-01],
       [1.64419657e-20, 9.31546074e-05, 2.23130160e-01, ...,
        2.23130160e-01, 1.00000000e+00, 1.00000000e+00],
       ...,
       [1.64419657e-20, 9.31546074e-05, 2.23130160e-01, ...,
        2.23130160e-01, 1.00000000e+00, 1.00000000e+00],
       [2.01995735e-15, 7.24397570e-02, 3.08485693e-03, ...,
        3.08485693e-03, 7.25488812e-05, 7.25488812e-05],
       [1.63543936e-16, 5.36067753e-04, 9.80365504e-03, ...,
        9.80365504e-03, 1.32678043e-03, 1.32678043e-03]])

In [7]:
X_test

array([[1.02618796e-10, 9.80013000e-07, 4.71486454e-02, ...,
        4.71486454e-02, 1.05202848e-02, 1.05202848e-02],
       [1.13574782e-14, 1.34902903e-01, 1.28163306e-01, ...,
        1.28163306e-01, 5.38331997e-03, 5.38331997e-03],
       [7.37779981e-05, 1.25203611e-12, 1.20986715e-06, ...,
        1.20986715e-06, 1.34404100e-08, 1.34404100e-08],
       ...,
       [1.62308132e-15, 2.40248899e-03, 1.00000000e+00, ...,
        1.00000000e+00, 2.23130160e-01, 2.23130160e-01],
       [1.43452197e-18, 3.67879441e-01, 6.53064216e-03, ...,
        6.53064216e-03, 2.53220477e-04, 2.53220477e-04],
       [3.30245710e-19, 3.96103470e-03, 6.06530660e-01, ...,
        6.06530660e-01, 3.67879441e-01, 3.67879441e-01]])

## **Radial Basis Function Neural Network**

In [9]:
from sklearn.neural_network import MLPRegressor

rbfnn = MLPRegressor(
    hidden_layer_sizes=18,
    activation='tanh',
)
rbfnn.fit(X_train, y_train)
y_rbf_train_pred = rbfnn.predict(X_train)
y_rbf_test_pred = rbfnn.predict(X_test)

F:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

## **General Metric Result**

In [12]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2 = r2_score(y_test, y_rbf_test_pred)
mae = mean_absolute_error(y_test, y_rbf_test_pred)
mse = mean_squared_error(y_test, y_rbf_test_pred)

print("R^2 score:", r2)
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)

R^2 score: 0.9226117160938029
Mean Absolute Error (MAE): 0.23502806002455037
Mean Squared Error (MSE): 0.37446423872933127