# **Left Wing Position**

## **Load LW Data**

In [32]:
import pandas as pd

lw_df = pd.read_csv('LW.csv', delimiter=';')
lw_df

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC,GOAL
0,0,0.00,0,0.0,0,0.0,1,0.00,2,1.0,2,1.0,4
1,0,0.00,2,0.5,0,0.0,0,0.00,0,0.0,2,1.0,3
2,0,0.00,0,0.0,0,0.0,1,1.00,0,0.0,0,0.0,1
3,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0
4,3,0.33,1,1.0,0,0.0,2,0.50,0,0.0,1,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,5,1.00,0,0.0,1,0.0,0,0.00,0,0.0,0,0.0,5
1143,0,0.00,0,0.0,0,0.0,1,1.00,0,0.0,1,1.0,2
1144,0,0.00,0,0.0,0,0.0,3,0.33,0,0.0,0,0.0,1
1145,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0
1146,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0

## **Prepare X and y**

In [33]:
X = lw_df.drop('GOAL', axis=1)
y = lw_df['GOAL']

In [34]:
X

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC
0,0,0.00,0,0.0,0,0.0,1,0.00,2,1.0,2,1.0
1,0,0.00,2,0.5,0,0.0,0,0.00,0,0.0,2,1.0
2,0,0.00,0,0.0,0,0.0,1,1.00,0,0.0,0,0.0
3,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0
4,3,0.33,1,1.0,0,0.0,2,0.50,0,0.0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1142,5,1.00,0,0.0,1,0.0,0,0.00,0,0.0,0,0.0
1143,0,0.00,0,0.0,0,0.0,1,1.00,0,0.0,1,1.0
1144,0,0.00,0,0.0,0,0.0,3,0.33,0,0.0,0,0.0
1145,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0
1146,0,0.00,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0

In [35]:
y

0       4
1       3
2       1
3       0
4       4
       ..
1142    5
1143    2
1144    1
1145    0
1146    0
Name: GOAL, Length: 1147, dtype: int64

## **Training set and Testing set**

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.gaussian_process.kernels import RBF

length_scale = 1.0
rbf_kernel = RBF(length_scale=length_scale)
X_rbf = rbf_kernel(X)

X_train, X_test, y_train, y_test = train_test_split(X_rbf, y, train_size=.8, random_state=42)

In [37]:
X_train

array([[1.98041274e-03, 2.88148354e-03, 1.73450173e-02, ...,
        1.27734677e-01, 1.20118105e-03, 1.20118105e-03],
       [2.47875218e-03, 8.04733010e-04, 6.06530660e-01, ...,
        4.84591021e-01, 8.20849986e-02, 8.20849986e-02],
       [2.07856025e-05, 1.11257313e-05, 1.70618615e-06, ...,
        1.84484572e-07, 6.27670807e-07, 6.27670807e-07],
       ...,
       [2.82383432e-07, 2.49202504e-07, 1.71274210e-07, ...,
        3.61911943e-08, 1.71274210e-07, 1.71274210e-07],
       [2.85970990e-02, 2.52368513e-02, 8.87559414e-03, ...,
        9.59690233e-04, 3.26514861e-03, 3.26514861e-03],
       [1.52299797e-08, 1.34404100e-08, 1.37095909e-06, ...,
        2.89691289e-07, 1.37095909e-06, 1.37095909e-06]])

In [38]:
X_test

array([[4.08677144e-03, 9.80365504e-03, 3.67879441e-01, ...,
        1.05202848e-02, 1.00000000e+00, 1.00000000e+00],
       [6.60565080e-05, 2.90232041e-06, 9.80365504e-03, ...,
        5.97829310e-01, 2.96044730e-04, 2.96044730e-04],
       [1.88902450e-06, 2.25611803e-07, 2.62757287e-06, ...,
        2.43008313e-05, 2.55651666e-07, 2.55651666e-07],
       ...,
       [1.50343919e-03, 3.60656314e-03, 1.35335283e-01, ...,
        3.87019649e-03, 3.67879441e-01, 3.67879441e-01],
       [4.08677144e-03, 9.80365504e-03, 3.67879441e-01, ...,
        1.05202848e-02, 1.00000000e+00, 1.00000000e+00],
       [4.08677144e-03, 9.80365504e-03, 3.67879441e-01, ...,
        1.05202848e-02, 1.00000000e+00, 1.00000000e+00]])

## **Radial Basis Function Neural Network**

In [39]:
from sklearn.neural_network import MLPRegressor

rbfnn = MLPRegressor(
    hidden_layer_sizes=18,
    activation='tanh',
)
rbfnn.fit(X_train, y_train)
rbfnn.score(X_test, y_test)

F:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.9513669872992684

## **General Metric Result**