### **Load CB Data**

In [7]:
import pandas as pd

cb_df=pd.read_csv('CB.csv',delimiter=';')
cb_df

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC,GOAL
0,0,0.0,3,1.00,9,0.33,0,0.0,0,0.0,0,0.0,6
1,0,0.0,4,0.75,0,0.00,0,0.0,1,1.0,0,0.0,4
2,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0,1
3,0,0.0,0,0.00,2,0.50,0,0.0,0,0.0,0,0.0,1
4,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,0,0.0,3,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0
1284,0,0.0,2,1.00,0,0.00,0,0.0,0,0.0,1,1.0,3
1285,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0,1
1286,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0
1287,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0,0

### **Prepare X and Y**

In [8]:
X = cb_df.drop('GOAL', axis=1)
y = cb_df['GOAL']

In [9]:
X

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC
0,0,0.0,3,1.00,9,0.33,0,0.0,0,0.0,0,0.0
1,0,0.0,4,0.75,0,0.00,0,0.0,1,1.0,0,0.0
2,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0
3,0,0.0,0,0.00,2,0.50,0,0.0,0,0.0,0,0.0
4,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1283,0,0.0,3,0.00,0,0.00,0,0.0,0,0.0,0,0.0
1284,0,0.0,2,1.00,0,0.00,0,0.0,0,0.0,1,1.0
1285,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0
1286,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
1287,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0

In [10]:
y

0       6
1       4
2       1
3       1
4       0
       ..
1283    0
1284    3
1285    1
1286    0
1287    0
Name: GOAL, Length: 1288, dtype: int64

### **Training Set and Testing Set**

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [12]:
X_train

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC
634,0,0.0,1,1.00,0,0.00,0,0.0,0,0.0,0,0.0
673,0,0.0,0,0.00,1,1.00,0,0.0,0,0.0,0,0.0
823,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
1150,0,0.0,0,0.00,4,0.75,0,0.0,0,0.0,0,0.0
135,0,0.0,2,1.00,0,0.00,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1044,0,0.0,3,1.00,0,0.00,0,0.0,0,0.0,0,0.0
1095,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
1130,0,0.0,0,0.00,0,0.00,0,0.0,0,0.0,0,0.0
860,0,0.0,4,0.25,1,0.00,1,1.0,0,0.0,0,0.0
1126,0,0.0,2,0.50,1,1.00,1,1.0,0,0.0,2,1.0

In [13]:
X_test

,7MSHOT,7MACC,6MSHOT,6MACC,9MSHOT,9MACC,WINGSHOT,WINGACC,PIVOTSHOT,PIVOTACC,FASTBREAKSHOT,FASTBREAKACC
1120,0,0.0,0,0.00,3,0.33,0,0.0,0,0.0,0,0.0
1185,0,0.0,3,0.67,1,0.00,0,0.0,0,0.0,0,0.0
462,0,0.0,0,0.00,6,0.50,0,0.0,0,0.0,0,0.0
81,0,0.0,4,0.75,1,1.00,0,0.0,0,0.0,0,0.0
63,0,0.0,1,0.00,2,0.50,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
163,0,0.0,1,0.00,1,0.00,0,0.0,0,0.0,0,0.0
1196,0,0.0,2,1.00,1,1.00,0,0.0,0,0.0,0,0.0
1081,0,0.0,1,1.00,1,0.00,0,0.0,0,0.0,0,0.0
352,0,0.0,4,0.75,0,0.00,0,0.0,0,0.0,0,0.0
342,0,0.0,1,1.00,0,0.00,0,0.0,0,0.0,0,0.0

### **Model RBFNN**

In [39]:
from sklearn.preprocessing import MinMaxScaler

# Perform feature scaling on the input features
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [49]:
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Create K-means clustering model
kmeans = KMeans(n_clusters=3, random_state=42)

# Create linear regression model
regressor = LinearRegression()

# Create the RBFNN model pipeline
model = make_pipeline(StandardScaler(), kmeans, regressor)

# Fit the RBFNN model to the training data
model.fit(X_train_scaled, y_train)

F:\Anaconda\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kmeans', KMeans(n_clusters=3, random_state=42)),
                ('linearregression', LinearRegression())])

In [50]:
# Make predictions on the test set
y_train_pred = model.predict(X_train_scaled)
y_test_pred = model.predict(X_test_scaled)

In [51]:
y_train_pred

array([ 1.54856142,  2.02192391, -0.4098843 , ..., -0.4098843 ,
        3.66163358,  4.25640947])

In [52]:
y_test_pred

array([ 1.33130813,  1.89875745,  2.77985656,  3.84225967,  1.43645287,
        2.0879537 ,  4.0911438 , -0.30524251,  2.88377337, -0.4098843 ,
       -0.4098843 ,  4.46876341,  3.24664953,  3.81640251,  3.84530759,
        4.23683564,  2.19362125,  2.55868539,  1.81649287,  1.47257766,
        3.58276479,  4.37865526,  2.19362125,  4.38861047,  2.15799229,
        0.44580898,  3.58536884,  1.54856142,  4.71924931,  1.89875745,
        2.82762812,  4.1598738 , -0.24122297,  2.58164248,  4.14504626,
        2.93296228,  2.79847981,  1.45140806,  1.89875745, -0.4098843 ,
        4.64174016, -0.4098843 ,  1.54856142, -0.4098843 , -0.4098843 ,
       -0.4098843 , -0.4098843 , -0.4098843 ,  2.02192391,  2.19362125,
       -0.4098843 ,  4.16402026,  2.71350166,  5.42691348, -0.4098843 ,
        3.29383364,  4.29249556,  1.86519441,  3.5809908 ,  2.19362125,
        2.36789269,  1.89875745,  4.23303068,  2.55868539,  2.51758716,
        4.9629042 ,  2.50544024,  0.96333746,  3.7729366 ,  4.10926039,
        1.81649287,  2.58164248,  0.27805931,  0.27805931,  4.16275176,
        5.38919679,  1.54856142,  3.24664953,  2.83489183, -0.4098843 ,
       -0.4098843 , -0.4098843 ,  5.34345953,  4.0361664 ,  4.29388069,
        4.19349085,  4.00729584,  3.32389719, -0.4098843 ,  2.23188237,
        3.03325105, -0.4098843 , -0.30524251, -0.4098843 ,  3.28859481,
        3.3203497 ,  1.54856142, -0.4098843 ,  4.01380921, -0.4098843 ,
        3.46972914,  3.57365359, -0.4098843 ,  1.81649287, -0.4098843 ,
        1.33130813,  2.88730713,  3.00017233,  2.49577337,  0.1294462 ,
        3.01885587, -0.4098843 ,  3.77241308,  6.30793961,  1.54856142,
       -0.30524251,  3.03773147, -0.4098843 ,  1.54856142,  3.17728652,
       -0.4098843 ,  1.20425838,  3.25416377, -0.4098843 ,  3.00017233,
        3.00017233,  1.89888796, -0.4098843 ,  1.81649287,  0.27805931,
       -0.30524251, -0.4098843 ,  2.4700424 , -0.4098843 ,  3.67256815,
       -0.4098843 ,  4.40019436, -0.4098843 ,  0.1294462 ,  3.7432386 ,
        4.65290246,  5.7412429 , -0.4098843 ,  4.13871887,  0.69691452,
        2.55868539, -0.4098843 , -0.4098843 , -0.24122297,  2.36789269,
        4.43449058,  2.84226802,  4.11300989,  5.59447445,  5.83836232,
       -0.4098843 ,  2.27607943,  2.02192391,  2.82093415,  2.81775671,
        5.9781963 ,  4.10538514, -0.4098843 ,  2.64121095,  2.47814987,
        5.26226566,  0.44580898,  1.54856142,  3.5874807 ,  6.24927268,
       -0.4098843 ,  0.66560891, -0.4098843 ,  3.57816202, -0.13022106,
        0.1294462 , -0.4098843 ,  2.58164248,  3.66146762,  1.54856142,
        1.33130813, -0.4098843 , -0.4098843 ,  1.81649287,  4.71782978,
       -0.24122297, -0.24122297,  0.44580898,  1.86519441,  3.75653664,
        3.36767919,  1.89875745,  2.23188237,  2.79847981,  3.48297841,
        1.86519441, -0.4098843 , -0.4098843 ,  1.7896725 ,  4.27915488,
        2.5255267 ,  2.2277962 ,  0.33593963, -0.24122297,  0.27805931,
        3.14372095,  3.33658085, -0.24122297, -0.4098843 , -0.4098843 ,
        4.20744857,  2.94302539,  2.23188237,  1.54856142,  1.81649287,
        3.01478275,  3.57467032, -0.4098843 ,  2.3229595 ,  3.81042681,
        4.14703877,  2.02192391, -0.24122297,  3.58403817,  1.54856142,
        3.44626192,  3.44626192,  1.54856142,  4.45214106,  5.82400138,
        1.58810799, -0.4098843 , -0.4098843 ,  2.27607943,  2.52476239,
        2.94302539,  3.81284732, -0.24122297, -0.4098843 , -0.4098843 ,
        0.83838036,  0.66560891,  2.77985656,  3.90800531,  2.55960707,
        2.71173869,  3.00017233, -0.4098843 ,  1.7896725 ,  1.86519441,
        3.43756939,  1.20425838, -0.4098843 , -0.13022106,  3.59231292,
        1.81649287,  2.19362125,  1.54856142])

**Evaluate**

In [53]:
from sklearn.metrics import mean_squared_error, r2_score

rbf_train_mse = mean_squared_error(y_train, y_train_pred)
rbf_train_r2 = r2_score(y_train, y_train_pred)

rbf_test_mse = mean_squared_error(y_test, y_test_pred)
rbf_test_r2 = r2_score(y_test, y_test_pred)

In [54]:
rbf_train_mse

0.9856000916485045

In [55]:
rbf_train_r2

0.7627143064426318

In [56]:
rbf_test_mse

1.0673842145390513

In [57]:
rbf_test_r2

0.779410090234416